src/Entity/Biere.php
<?php

namespace App\Entity;

use ArrayAccess;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\BiereRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * @ORM\Entity(repositoryClass=BiereRepository::class)
 */
class Biere implements ArrayAccess
{

    const   PROJET      =   0;
    const   PRETE       =   1;
    const   LANCEE      =   2;
    const   EMPATEE     =   3;
    const   RINCEE      =   4;
    const   HOUBLONNEE  =   5;
    const   FERMENTEE   =   6;
    const   BRASSEE     =   7;
    const   STOP        =   10;
    // const   EMBOUTEILLEE   =   7;
    // const   BRASSEE     = 8;

    private $container = array();

   
     /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="date")
     */
    private $dateAjout;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $dateBrassage;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $dateBrassee;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity=TypeBiere::class, inversedBy="bieres")
     * @ORM\JoinColumn(nullable=false)
     */
    private $type;

//    /**
//     * @ORM\OneToMany(targetEntity=IngRecette::class, mappedBy="idBiere")
//     */
//    private $ingRecettes;

    // /**
    //  * @ORM\OneToMany(targetEntity=Ingredient::class, mappedBy="idBiere")
    //  */
    // private $ingredientsPourRecettes;

    // /**
    //  * @ORM\OneToMany(targetEntity=Ingredient::class, mappedBy="biere")
    //  */
    // private $ingredients;

    /**
     * @ORM\Column(type="string")
     */
    private $state;

    // /**
    //  * @ORM\Column(type="boolean")
    //  */
    // private $ingredientState;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="bieres")
     * @ORM\JoinColumn(nullable=false)
     */
    private $User;

    // /**
    //  * @ORM\OneToOne(targetEntity=Brassage::class, mappedBy="biere", cascade={"persist", "remove"})
    //  */
    // private $brassage;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $currentPlace;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $volFinalPrevu;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $tpsEmpatage;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $volH2OEmpatage;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $volH2ORincage;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $volHoublonnage;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $tpsHoublonnage;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $dInitiale;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $volFermentation;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $tpsFermentation;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $dFinale;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $sucre;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $volFinalObtenu;

    /**
     * @ORM\OneToMany(targetEntity=Palier::class, mappedBy="biere")
     */
    private $paliers;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $transition;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $poidsGrain;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $volEmpatage;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $dRincage;

    public function __construct($valeurs = array())
    // public function __construct()
    {
        if (!empty($valeurs)) {
            $this->hydrate($valeurs);
        }
        // $this->ingredients = new ArrayCollection();
        $this->paliers = new ArrayCollection();

    }

    // public function __construct()
    // {
    //     $this->container = array(
    //         "one"   => 1,
    //         "two"   => 2,
    //         "three" => 3,
    //     );
    // }

    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }


    // public function offsetExists($offset) { }

    // public function offsetGet($offset) { }

    // public function offsetSet($offset, $value) { }

    // public function offsetUnset($offset) { }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDateAjout(): ?\DateTimeInterface
    {
        return $this->dateAjout;
    }

    public function setDateAjout(\DateTimeInterface $dateAjout): self
    {
        $this->dateAjout = $dateAjout;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getType(): ?typeBiere
    {
        return $this->type;
    }

    public function setType(?typeBiere $type): self
    {
        $this->type = $type;

        return $this;
    }

    // /**
    //  * @return Collection|Ingredient[]
    //  */
    // public function getIngredientsPourRecettes(): Collection
    // {
    //     return $this->ingredientsPourRecettes;
    // }

    // public function addIngredientsPourRecette(Ingredient $ingredientsPourRecette): self
    // {
    //     if (!$this->ingredientsPourRecettes->contains($ingredientsPourRecette)) {
    //         $this->ingredientsPourRecettes[] = $ingredientsPourRecette;
    //         $ingredientsPourRecette->setIdBiere($this);
    //     }

    //     return $this;
    // }

    // public function removeIngredientsPourRecette(Ingredient $ingredientsPourRecette): self
    // {
    //     if ($this->ingredientsPourRecettes->removeElement($ingredientsPourRecette)) {
    //         // set the owning side to null (unless already changed)
    //         if ($ingredientsPourRecette->getIdBiere() === $this) {
    //             $ingredientsPourRecette->setIdBiere(null);
    //         }
    //     }

    //     return $this;
    // }

    
    // /**
    //  * @return Collection|Ingredient[]
    //  */
    // public function getIngredients(): Collection
    // {
    //     return $this->ingredients;
    // }

    // public function addIngredient(Ingredient $ingredient): self
    // {
    //     if (!$this->ingredients->contains($ingredient)) {
    //         $this->ingredients[] = $ingredient;
    //         $ingredient->setBiereId($this->id);
    //     }

    //     return $this;
    // }

    // public function removeIngredient(Ingredient $ingredient): self
    // {
    //     if ($this->ingredients->removeElement($ingredient)) {
    //         // set the owning side to null (unless already changed)
    //         if ($ingredient->getBiereId() === $this->id) {
    //             $ingredient->setBiereId(null);
    //         }
    //     }

    //     return $this;
    // }

    public function getState()
    {
        return $this->state;
    }

    public function setState($state): self
    {
        $this->state = $state;

        return $this;
    }

    // public function getIngredientState(): ?bool
    // {
    //     return $this->ingredientState;
    // }

    // public function setIngredientState(bool $ingredientState): self
    // {
    //     $this->ingredientState = $ingredientState;

    //     return $this;
    // }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    // public function getBrassage(): ?Brassage
    // {
    //     return $this->brassage;
    // }

    // public function setBrassage(Brassage $brassage): self
    // {
    //     // set the owning side of the relation if necessary
    //     if ($brassage->getBiere() !== $this) {
    //         $brassage->setBiere($this);
    //     }

    //     $this->brassage = $brassage;

    //     return $this;
    // }

    public function getCurrentPlace(): ?string
    {
        return $this->currentPlace;
    }

    public function setCurrentPlace(?string $currentPlace): self
    {
        $this->currentPlace = $currentPlace;

        return $this;
    }
    

    /**
     * Get the value of dateBrassage
     */ 
    public function getDateBrassage()
    {
        return $this->dateBrassage;
    }

    /**
     * Set the value of dateBrassage
     *
     * @return  self
     */ 
    public function setDateBrassage($dateBrassage)
    {
        $this->dateBrassage = $dateBrassage;

        return $this;
    }

    /**
     * Get the value of dateBrassee
     */ 
    public function getDateBrassee()
    {
        return $this->dateBrassee;
    }

    /**
     * Set the value of dateBrassee
     *
     * @return  self
     */ 
    public function setDateBrassee($dateBrassee)
    {
        $this->dateBrassee = $dateBrassee;

        return $this;
    }

templates/base.html.twig
<!doctype html>
<html lang="fr">
{% use "includes/include.html.twig" %}
{# {% use "includes/classes.html.twig" %} #}
{# {% set buttonShape = "btn btn-outline-warning" %} #}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {# <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script> #}
{#    <script src="{{ asset('assets/js/jquery-3.5.1.js') }}"></script>#}
{#    <meta name="description" content="">#}
{#    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">#}
{#    <meta name="generator" content="Hugo 0.79.0">#}
    {%set siteName = "My 8eers"%}
    
    <title>My 8eers</title>

    {% block stylesheets %}
        {# 'app' must match the first argument to addEntry() in webpack.config.js #}
        {{ encore_entry_link_tags('app') }}

        <!-- Renders a link tag (if your module requires any CSS)
                <link rel="stylesheet" href="/build/app.css"> -->
    {% endblock %}

    {% block javascripts %}
        {{ encore_entry_script_tags('app') }}

        <!-- Renders app.js & a webpack runtime.js file
            <script src="/build/runtime.js" defer></script>
            <script src="/build/app.js" defer></script>
            See note below about the "defer" attribute -->
    {% endblock %}
    <!-- Bootstrap core CSS -->
    {# <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous"> #}

</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-warning">
    <div class="container">
        <a class="navbar-brand" href ={{ path('home') }}>
            <img src={{ asset('build/Logo_bière.svg') }} style="width : 50px">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{ path('home') }}">Accueil</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href={{ path('indexBiere') }}>Ma brasserie</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href={{ path('indexStock') }}>Mes stocks</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Les recettes existantes</a>
                </li>
            </ul>
            <div class="nav-item text-dark d-flex align-items-center mb-2 mb-lg-0">
                {% if app.user %}
                    <a class="nav-link text-dark" href = "{{path('account')}}">Mon compte <small>({{app.user.username}})</small></a> | <a class="nav-link text-dark" href = "{{path('app_logout')}}">Déconnexion</a>
                {% else %}
                    <a class="nav-link text-dark" href = "{{path('app_login')}}">Connexion</a> | <a class="nav-link text-dark" href = "{{path('inscription')}}">Inscription</a>
                {% endif %}                   
            </div>
        </div>

        {# <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <a class="navbar-brand" href ={{ path('home') }}>
                My-8eers
            </a>
            <ul class="navbar-nav">
                <li class="nav-pill">
                    <a class="nav-link active" aria-current="page" href={{ path('home') }}>Accueil</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href={{ path('indexBiere') }}>Ma brasserie</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href={{ path('indexStock') }}>Mes stocks</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Les recettes existantes</a>
                </li>
            </ul>
            <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
            <div class="nav-item">
                {% if app.user %}
                    <a  href = "{{path('account')}}">Mon compte <small>({{app.user.username}})</small></a> | <a href = "{{path('app_logout')}}">Déconnexion</a>
                {% else %}
                    <a  href = "{{path('app_login')}}">Connexion</a> | <a  href = "{{path('inscription')}}">Inscription</a>
                {% endif %}                   
            </div>
        </div> #}
    </div>
</nav>




  {# <ul class="nav nav-pills flex-column mb-auto">
    <li class="nav-item">
      <a href="#" class="nav-link active">
        <svg class="bi me-2" width="16" height="16"><use xlink:href="#home"/></svg>
        Home
      </a>
    </li>
    <li>
      <a href="#" class="nav-link text-white">
        <svg class="bi me-2" width="16" height="16"><use xlink:href="#speedometer2"/></svg>
        Dashboard
      </a>
    </li>
    <li>
      <a href="#" class="nav-link text-white">
        <svg class="bi me-2" width="16" height="16"><use xlink:href="#table"/></svg>
        Orders
      </a>
    </li>
    <li>
      <a href="#" class="nav-link text-white">
        <svg class="bi me-2" width="16" height="16"><use xlink:href="#grid"/></svg>
        Products
      </a>
    </li>
    <li>
      <a href="#" class="nav-link text-white">
        <svg class="bi me-2" width="16" height="16"><use xlink:href="#people-circle"/></svg>
        Customers
      </a>
    </li>
  </ul>
  <hr>
  <div class="dropdown">
    <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
      <img src="https://github.com/mdo.png" alt="mdo" width="32" height="32" class="rounded-circle me-2">
      <strong>mdo</strong>
    </a>
    <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
      <li>
        <a class="dropdown-item" href="#">New project...</a>
      </li>
      <li>
        <a class="dropdown-item" href="#">Settings</a>
      </li>
      <li>
        <a class="dropdown-item" href="#">Profile</a>
      </li>
      <li><hr class="dropdown-divider"></li>
      <li>
        <a class="dropdown-item" href="#">Sign out</a>
      </li>
    </ul>
  </div>
</div> #}

 {# style ="background : #198454"> #}


{# <nav class="navbar sticky-top navbar-expand-md navbar-light bg-warning">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{path('home')}}" >
                <img src="{{ asset('build/Logo_bière.svg') }}" style ="height: 75px"  alt="logo 8eers">
                My 8eers
        </a>
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
            <li class="nav-item">
                <a class="nav-link" href="{{path('indexBiere')}}">Ma brasserie</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{path('indexStock')}}">Mon stocke</a>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled" href="#">Recettes existante</a>
            </li>
        </ul>

            {% if app.user %}                
                <div class = "d-flex flex-row align-items-center "><a  class = "nav-link" href = "{{path('account')}}">Mon compte <small>({{app.user.Username}})</small></a> | <a class = "nav-link" href = "{{path('app_logout')}}">Déconnexion</a></div>
            {% else %}
                <a  class = "nav-link" href = "{{path('app_login')}}">Connexion</a> | <a  class = "nav-link" href = "{{path('inscription')}}">Inscription</a>
            {% endif %}
    </div>
</nav> #}


<div class="container-fluid">
    {# <aside>
        <div class="d-flex flex-column p-3 text-dark bg-warning" style="width: 280px;">
            <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-dark text-decoration-none">
                <img src={{ asset('build/Logo_bière.svg') }} style="width : 50px">
                <span class="fs-4">My-8eers</span>
            </a>
            <hr>
            <ul class="nav nav-pills flex-column mb-auto">
                <li class="nav-item">
                    <a class="nav-link active text-dark" aria-current="page" href={{ path('home') }}>
                        <i class="fas fa-home"></i>
                        Accueil
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" href={{ path('indexBiere') }}>
                        <i class="fas fa-beer"></i>
                        Ma brasserie
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" href={{ path('indexStock') }}><i class="fas fa-warehouse"></i>Mes stocks</a>
                </li>
                <li class="nav-item ">
                    <a class="nav-link text-dark" href="#"><i class="fas fa-blender"></i>Les recettes existantes</a>
                </li>
            </ul>
        </div>
    </aside> #}
    <main>
        {% block contents %}{% endblock %}
    </main>
</div>




<!-- jQuery first, then Popper.js, then Bootstrap JS -->

{# <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script> #}
<script>
    var pathname = window.location.pathname;
    console.log(pathname);
    pages = ['brasserie', 'stock','recettes'];

    document.getElementsByClassName('nav-link').foreach(function(i) {
    if (pathname.includes(pages[i])) this.addClass('active');
    else if (this.className.includes('active')) this.removeClass('active');
    });
</script>
</body>
</html>

templates/blocks.html.twig
{% block ajouterLink %}
    <a name="ajouterLink" href="{{ path('addTypeBiere') }}" id="ajouterLink">
         Ajouter
    </a>
{% endblock %}

templates/message.html.twig
{% extends 'base.html.twig' %}

{% block title %}My-8eers{% endblock %}

{% block contents %}
        {% if messageId == 1 %}
            <div class="alert alert-danger">
                Des bières utilisent cet ingrédient:</br>
                {{ ingredient.nom }}
            </div>
            <p>
                <a href="{{ path('viewStock', {'ingredientType': ingredientType} )}}" >
                    Retour à la liste des {{ ingredientType|lower }}.
                </a>
            </p>
        {% endif %}
{% endblock %}